### ISSUE TITLE
Important! - Curator names are incorrect

### ISSUE THREAD

**Issue by Dutchessofcrush** [BlindBoxesNFT/blindboxes-contracts#12]
We have spotted several collections where the curator name is not correct. Can we fix this ASAP. 

The curator of this collection is not Hashlips. The name should be "Itsvolpart". 
![image](https://user-images.githubusercontent.com/88632652/129493008-af90270a-9b70-4141-9f42-2899d018aadd.png)

**Comment by BriefCandle** [comment]
This issue will be fixed when issue #9 is fixed.
