### ISSUE TITLE
Typo: Buying popup

### ISSUE THREAD

**Issue by Dutchessofcrush** [BlindBoxesNFT/blindboxes-contracts#13]
![image](https://user-images.githubusercontent.com/88632652/129493328-e48e993d-4066-4a7b-a052-a19f8637617c.png)

The text here should say "Draw a Blind Box from this collection"

**Comment by BriefCandle** [comment]
> ![image](https://user-images.githubusercontent.com/88632652/129493328-e48e993d-4066-4a7b-a052-a19f8637617c.png)
> 
> The text here should say "Draw a Blind Box from this collection"

It will be: Draw a Blind Box from "Blockchain Cuties Universe". or whatever the name of the collection is.

We will also reformat the page layout.
