### ISSUE TITLE
Extremely high gas fees on the Blockchain Cuties collection

### ISSUE THREAD

**Issue by Dutchessofcrush** [BlindBoxesNFT/blindboxes-contracts#14]
I get a $53 ETH fee when trying to draw from the blockchain cuties collection. When I switch to a different browser / different Metamask, the fee is only $16. But even in the second case, the transaction still does not go through. This collection ends in 10 hours, so it is very important that we fix this ASAP.

![image](https://user-images.githubusercontent.com/88632652/129494841-7a38e3d6-ca4f-4ea6-9a0c-4984553a6a99.png)

**Comment by BriefCandle** [comment]
> I get a $53 ETH fee when trying to draw from the blockchain cuties collection. When I switch to a different browser / different Metamask, the fee is only $16. But even in the second case, the transaction still does not go through. This collection ends in 10 hours, so it is very important that we fix this ASAP.
> 
> ![image](https://user-images.githubusercontent.com/88632652/129494841-7a38e3d6-ca4f-4ea6-9a0c-4984553a6a99.png)

Normally, Metamask provides an estimate of the gas fee based on the current traffic situation. The estimated gas fee swings up when the traffic gets congested, and it goes low when the traffic goes slow. However, like a bidding system, there is no guarantee that your bid or your proposed transaction will go through. This is a major problem for the ETH network. It would get better in the BSC or Polygon network.
