### ISSUE TITLE
Curator name and profile photo - Blockchain Cuties

### ISSUE THREAD

**Issue by Dutchessofcrush** [BlindBoxesNFT/blindboxes-contracts#16]
Ethereum based collection - https://v2.blindboxes.io/collectiondetail/1/3

1. The curator should display: Blockchain Cuties
2. The profile image should be:
![Steve](https://user-images.githubusercontent.com/88632652/129556331-ec331029-bd06-4016-b7ed-4f59a3084f14.png)

**Comment by BriefCandle** [comment]
> https://v2.blindboxes.io/collectiondetail/1/3

Do you mean "https://v2.blindboxes.io/collectiondetail/1/6" instead?
