### ISSUE TITLE
Remove collection (and return the NFTs): Mai Solsona

### ISSUE THREAD

**Issue by Dutchessofcrush** [BlindBoxesNFT/blindboxes-contracts#17]
ASAP please remove this collection. It is expired. The NFTs must be returned to the users because we is going to relist them.  https://v2.blindboxes.io/collectiondetail/0/118  This is on BSC.  
![image](https://user-images.githubusercontent.com/88632652/129672790-0e4b9372-9f77-4f1a-bdc7-b9c55c2277d9.png)

**Comment by BlindBoxes** [comment]
Done
