### ISSUE TITLE
Add Artist Name and profile photo - Dusty Kessler

### ISSUE THREAD

**Issue by Dutchessofcrush** [BlindBoxesNFT/blindboxes-contracts#18]
This is the address of Dusty Kessler. He is a famous creator on our platform.  0xa1035Aa2E4750a6482DB805321824815c73B22B7

1. Name: Dusty Kessler
2. Profile image:

![image](https://user-images.githubusercontent.com/88632652/129713126-21b6c7a7-b5ec-4332-87a9-c60fd6f836f0.png)

**Comment by BriefCandle** [comment]
> * Name: Dusty Kessler
> 
> * Profile image:

Will do it soon
