### ISSUE TITLE
Issue with the token claiming site 

### ISSUE THREAD

**Issue by Dutchessofcrush** [BlindBoxesNFT/blindboxes-contracts#2]
https://claim.blindboxes.io - User is no longer able to see claimable tokens.

**Comment by BriefCandle** [comment]
> https://claim.blindboxes.io - User is no longer able to see claimable tokens.

Hello, there. Could you be a a little more specific about the issue or provide me with a screenshot please? Thanks.

**Comment by Dutchessofcrush** [comment]
![image](https://user-images.githubusercontent.com/88632652/128681860-708a31a6-c6ca-4cbd-8f26-f9d30688e1bb.png)

**Comment by Dutchessofcrush** [comment]
The user is not able to see the tokens which he should be able to claim (as a private sale investor).

**Comment by BriefCandle** [comment]
Staking pool is updated
