### ISSUE TITLE
ASAP - Add cover to 4 collections - Polygon Punks ASAP - These are very important collections

### ISSUE THREAD

**Issue by Dutchessofcrush** [BlindBoxesNFT/blindboxes-contracts#21]
These are all on Polygon. They need covers asap as major PR is about to start. If you have questions just ask.

1. Polygon Punks Collection I - https://v2.blindboxes.io/collectiondetail/2/9 - 
![image](https://user-images.githubusercontent.com/88632652/130191224-77f94ec6-c76e-4df8-8563-fa949f61f61a.png)

2. Polygon Punks II - https://v2.blindboxes.io/collectiondetail/2/10
https://v2.blindboxes.io/collectiondetail/2/10
![image](https://user-images.githubusercontent.com/88632652/130192686-315b5c79-3db0-49a6-ba97-cbd3a61b48ab.png)

3. Polygon Punks III - https://v2.blindboxes.io/collectiondetail/2/11
![image](https://user-images.githubusercontent.com/88632652/130192386-94867c00-2706-42f6-9ea0-0f2b78265048.png)

4. PolygonPunks IV - https://v2.blindboxes.io/collectiondetail/2/13
![image](https://user-images.githubusercontent.com/88632652/130192267-62890ae8-46da-4351-8c4f-c6440b7ce421.png)

**Comment by BlindBoxes** [comment]
Done
