### ISSUE TITLE
Missing profile photo - Mai Solana

### ISSUE THREAD

**Issue by Dutchessofcrush** [BlindBoxesNFT/blindboxes-contracts#4]
1.  0xF139E45c65e6803Bc17307635c6629dB0972F3C2, Mai Solana, 
![image](https://user-images.githubusercontent.com/88632652/128671631-2b502e95-33cb-4d73-8f31-c9e158117051.png)

**Comment by BriefCandle** [comment]
>     1. 0xF139E45c65e6803Bc17307635c6629dB0972F3C2, Mai Solana,
>        ![image](https://user-images.githubusercontent.com/88632652/128671631-2b502e95-33cb-4d73-8f31-c9e158117051.png)

Will look into this issue and resolve it.
