### ISSUE TITLE
Missing Collection Cover - Eva Milkaa

### ISSUE THREAD

**Issue by Dutchessofcrush** [BlindBoxesNFT/blindboxes-contracts#6]
1. Please add the below image as the cover image for this collection (on BSC): https://v2.blindboxes.io/collectiondetail/0/140
![80d6ccc41be6494b8a8f7df55790d9a9](https://user-images.githubusercontent.com/88632652/128824330-7bd82189-81c3-435c-9659-51f5df62c469.jpg)

2. Please add this image as the profile photo for the address that uploaded this collection.

![Chaos](https://user-images.githubusercontent.com/88632652/128824362-5bdccf6a-cb88-4cdf-af23-b3daa72d95fc.png)

**Comment by Dutchessofcrush** [comment]
Can I have an update on when this will be completed?

**Comment by BriefCandle** [comment]
> Can I have an update on when this will be completed?

Hi, do we know the collection name of the second picture?
