### ISSUE TITLE
Remove/Hide collection - Copyright issues

### ISSUE THREAD

**Issue by Dutchessofcrush** [BlindBoxesNFT/blindboxes-contracts#7]
This cover contains trademarked images from major brands. It violates copyright and makes the olatform and the artist liable for being sued. This collection shold be closed, or hidden from the platform immediately.  https://v2.blindboxes.io/collectiondetail/0/159
![image](https://user-images.githubusercontent.com/88632652/129320815-7d4ca21e-b9b0-4919-b658-9b459ad71ae3.png)

**Comment by BriefCandle** [comment]
Removed
