### ISSUE TITLE
Missing user icon and name - Volpart

### ISSUE THREAD

**Issue by Dutchessofcrush** [BlindBoxesNFT/blindboxes-contracts#9]
1. Need to add the username "Itsvolpart" for this address: 0x24a6746194388b03f5D572B676ce544DDCdc2752
2. Need to add this icon image to this user:  
![image](https://user-images.githubusercontent.com/88632652/129365273-54daca89-36a7-4196-a8b9-a16d2130b118.png)

**Comment by BriefCandle** [comment]
Working on it. The updae will go live soon.

**Comment by Dutchessofcrush** [comment]
Please let me know when both of these are finished. The users is asking me everyday now.

**Comment by Dutchessofcrush** [comment]
Please check on this. It has not been completed yet.
